import type { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    title: "Tai nghe không dây AirSound",
    description: "Tai nghe nhỏ gọn, pin dùng đến 24 giờ.",
    price: 1200000,
    discountPercentage: 10,
    rating: 4.8,
    stock: 24,
    category: "Âm thanh",
    thumbnail: "https://placehold.co/640x480/e5e7eb/475569?text=AirSound",
    images: [],
  },
  {
    id: 2,
    title: "Bình giữ nhiệt Travel Mug",
    description: "Giữ nóng và lạnh hiệu quả khi di chuyển.",
    price: 850000,
    discountPercentage: 5,
    rating: 4.6,
    stock: 12,
    category: "Đời sống",
    thumbnail: "https://placehold.co/640x480/e5e7eb/475569?text=Travel+Mug",
    images: [],
  },
  {
    id: 3,
    title: "Loa Bluetooth Mini",
    description: "Âm thanh sống động, chống nước chuẩn IPX7.",
    price: 2500000,
    discountPercentage: 0,
    rating: 4.9,
    stock: 8,
    category: "Âm thanh",
    thumbnail: "https://placehold.co/640x480/e5e7eb/475569?text=Bluetooth+Speaker",
    images: [],
  },
  {
    id: 4,
    title: "Đèn bàn Focus Light",
    description: "Ánh sáng dịu, phù hợp cho góc làm việc.",
    price: 690000,
    discountPercentage: 0,
    rating: 4.5,
    stock: 0,
    category: "Không gian sống",
    thumbnail: "https://placehold.co/640x480/e5e7eb/475569?text=Focus+Light",
    images: [],
  },
];
